// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCab6g7UQYISnd2vbOzuaZz0-xeEOqGYL4',
    appId: '1:614334604728:web:9c223fb971007b0ea85b4d',
    messagingSenderId: '614334604728',
    projectId: 'booking-app-a72d4',
    authDomain: 'booking-app-a72d4.firebaseapp.com',
    storageBucket: 'booking-app-a72d4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkJJxvxpmDYqGWwF2EaBvjS7O15r2ka2Q',
    appId: '1:614334604728:android:32676099a160ebe5a85b4d',
    messagingSenderId: '614334604728',
    projectId: 'booking-app-a72d4',
    storageBucket: 'booking-app-a72d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCkoWEQ66_E5euWG4xFXa8p10TNP1Y4XI',
    appId: '1:614334604728:ios:fac4e9c1ff664a82a85b4d',
    messagingSenderId: '614334604728',
    projectId: 'booking-app-a72d4',
    storageBucket: 'booking-app-a72d4.firebasestorage.app',
    iosBundleId: 'com.example.madProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCkoWEQ66_E5euWG4xFXa8p10TNP1Y4XI',
    appId: '1:614334604728:ios:fac4e9c1ff664a82a85b4d',
    messagingSenderId: '614334604728',
    projectId: 'booking-app-a72d4',
    storageBucket: 'booking-app-a72d4.firebasestorage.app',
    iosBundleId: 'com.example.madProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCab6g7UQYISnd2vbOzuaZz0-xeEOqGYL4',
    appId: '1:614334604728:web:8cc86203141f54c2a85b4d',
    messagingSenderId: '614334604728',
    projectId: 'booking-app-a72d4',
    authDomain: 'booking-app-a72d4.firebaseapp.com',
    storageBucket: 'booking-app-a72d4.firebasestorage.app',
  );
}
